identifier: xyz.thrzl.listenbrainz
name: ListenBrainz Enhanced
description: Plugin to submit listening data to ListenBrainz
author: thrzl
repo: https://github.com/thrzl/cider-listenbrainz
entry:
  "plugin.js":
    type: main